<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QCHandleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['name' => "Trả lựa phôi outdoor hạ cấp về sản phẩm khác", 'type' => "CBG"],
            ['name' => "Cắt khuyết tật ghép", 'type' => "CBG"],
            ['name' => "Cắt lựa bội số 1", 'type' => "CBG"],
            ['name' => "Cắt lựa về chân", 'type' => "CBG"],
            ['name' => "Cắt lựa về nắp", 'type' => "CBG"],
            ['name' => "Chuyển  NM khác   xử lí", 'type' => "CBG"],
            ['name' => "Chuyển trả NM Thái Bình xử lí", 'type' => "CBG"],
            ['name' => "Chuyển NM Việt Hà xử lí", 'type' => "CBG"],
            ['name' => "Chuyển nguyên liệu đốt lò", 'type' => "CBG"],
            ['name' => "Cắt lựa xay tiêu", 'type' => "CBG"],
            ['name' => "Hạ cấp cắt lựa bàn N", 'type' => "CBG"],
            ['name' => "Rong ghép lại", 'type' => "CBG"],
            ['name' => "Hạ cấp giằng TYBYN bar table", 'type' => "CBG"],
            ['name' => "Hạ cấp về thớt 350", 'type' => "CBG"],
            ['name' => "Hạ cấp về chân đôn ngắn", 'type' => "CBG"],
            ['name' => "Hạ cấp về chân tray", 'type' => "CBG"],
            ['name' => "Hạ cấp về mặt đôn", 'type' => "CBG"],
            ['name' => "Hạ cấp về vai bench", 'type' => "CBG"],
            ['name' => "Hạ cấp đầu nối trên chân Chair", 'type' => "CBG"],
            ['name' => "Hạ cấp về  giằng chair", 'type' => "CBG"],
            ['name' => "Hạ cấp về bọ đôn", 'type' => "CBG"],
            ['name' => "Hạ cấp mặt", 'type' => "CBG"],
            ['name' => "Chuyển trả NM Yên Sơn 1 xử lí", 'type' => "CBG"],
            ['name' => "Hạ cấp cạnh", 'type' => "CBG"],
            ['name' => "Rong ghép về mặt đôn", 'type' => "CBG"],
            ['name' => "Chà hạ cấp", 'type' => "CBG"],
            ['name' => "Chuyển vá xử lí", 'type' => "CBG"],
            ['name' => "Chuyển tinh chế vá ", 'type' => "CBG"],
            ['name' => "Hạ cấp mặt đôn", 'type' => "CBG"],
            ['name' => "Chuyển lăn sơn lại", 'type' => "CBG"],
            ['name' => "Chuyển hoàn thiện mộc trà xử lí", 'type' => "CBG"],
            ['name' => "Chà hạ cấp", 'type' => "CBG"],
            ['name' => "Chuyển tinh chế xử lí", 'type' => "CBG"],
            ['name' => "Chuyển NM Nam Hồng xử lí", 'type' => "CBG"],
            ['name' => "Chuyển NM Quang minh xử lí", 'type' => "CBG"],
            ['name' => "Chuyển ghép về chân bàn Tybyn", 'type' => "CBG"],
            ['name' => "Xếp sấy lại", 'type' => "CBG"],
            ['name' => "Chuyển lắp ráp thay thế chi tiết lỗi bằng chi tiết đạt", 'type' => "CBG"],
            ['name' => "Chuyển làm ván ghép thanh", 'type' => "CBG"],
            ['name' => "Chuyển trả lựa phôi", 'type' => "CBG"],
            ['name' => "Chuyển tinh chế xếp palet chờ xử lí", 'type' => "CBG"],
            ['name' => "Chuyển lựa phôi indoor", 'type' => "CBG"],
            ['name' => "Chuyển lựa phôi hạ cấp sản phẩm có quy cách nhỏ hơn", 'type' => "CBG"],
            ['name' => "Uốn lại", 'type' => "CBG"],
            ['name' => "Duỗi thẳng chuyển làm lõi chân, giằng....", 'type' => "CBG"],
            ['name' => "Xuất bán", 'type' => "CBG"],
            ['name' => "Xuất làm Block", 'type' => "CBG"],
            ['name' => "Xuất làm VGT", 'type' => "CBG"],
            ['name' => "Rong chuyển về làm lõi chân rằng", 'type' => "CBG"],
            ['name' => "Rong ghép dọc chuyển làm vỏ bước 2", 'type' => "CBG"],
            ['name' => "Hạ cấp", 'type' => "CBG"],
            ['name' => "Cắt bỏ đầu mộng chuyển về ván ghép Thanh Indoor", 'type' => "CBG"],
            ['name' => "Cắt bỏ lỗ khoan chuyển về ván ghép Thanh Indoor", 'type' => "CBG"],
            ['name' => "Cắt bỏ đầu mộng chuyển về ván ghép thanh", 'type' => "CBG"],
            ['name' => "Cắt bỏ lỗ khoan chuyển về ván ghép thanh", 'type' => "CBG"],
            ['name' => " hạ cấp về (410-58-19),phần cắt còn lại chuyển VGT", 'type' => "CBG"],
            ['name' => "Trả lại tổ runnen xử lý", 'type' => "CBG"],
            ['name' => "Hạ cấp về 564-48-19, phần còn lại hạ cấp về quy cách liền kề", 'type' => "CBG"],
            ['name' => "hạ cấp về chân stackholmen 393", 'type' => "CBG"],
            ['name' => "hạ cấp về giằng stackholmen 331", 'type' => "CBG"],
            ['name' => "Hạ cấp về ghép lớp vỏ ngoài giằng normanso", 'type' => "CBG"],
            ['name' => "Xuất duỗi uốn", 'type' => "CBG"],
            ['name' => "Chuyển nhà máy OKAL (băm dăm)", 'type' => "CBG"],
            ['name' => "Duỗi thẳng chuyển về làm vỏ ngoài chân giằng bàn N", 'type' => "CBG"],
            ['name' => "Hạ cấp 447*60*25, phần còn lại  chuyển làm khung xương khuôn cửa", 'type' => "CBG"],
            ['name' => "hạ cấp về Nan tựa lưng đứng Rocking chair (10*35*474)", 'type' => "CBG"],
            ['name' => "Cắt - rong hạ cấp ghép chân Rocking chair", 'type' => "CBG"],
            ['name' => "Bào hạ cấp làm thanh kê xếp sấy", 'type' => "CBG"],
            ['name' => "Chuyển làm chốt gỗ", 'type' => "CBG"],
            ['name' => "Chuyển về làm lõi chân giằng bàn N", 'type' => "CBG"],
            ['name' => "Chuyển lựa phôi cắt ghép về chân ngang (795x100x18)", 'type' => "CBG"],
            ['name' => "Chuyển lựa phôi sấy lại cắt ghép về Tjiusig", 'type' => "CBG"],
            ['name' => "Cắt ghép về nan tựa lưng 1,2,3 của ADIRONDACK", 'type' => "CBG"],
            ['name' => "Phun sơn lại", 'type' => "CBG"],
            ['name' => "Cắt ghép nam ngồi PorchSwing", 'type' => "CBG"],
            ['name' => "Phôi loại", 'type' => "CBG"],
            ['name' => "Chuyển NM Thái Bình duỗi", 'type' => "CBG"],
            ['name' => "Hạ cấp về 25*95*700 chân dưới NacKaNas", 'type' => "CBG"],
            ['name' => "Cắt hạ cấp làm giằng chân Rockingchair", 'type' => "CBG"],
            ['name' => "chuyển làm lõi xà giường", 'type' => "CBG"],
            ['name' => "Hạ cấp về khuôn xương cửa", 'type' => "CBG"],
            ['name' => "Hạ cấp về vai giường, xà giường", 'type' => "CBG"],
            ['name' => "Lọc lại", 'type' => "CBG"],
            ['name' => "Cắt hạ cấp về quy cách khác", 'type' => "CBG"],
            ['name' => "Hạ cấp làm thanh ghép ngoài 19x25x246.", 'type' => "CBG"],
            ['name' => "Hạ cấp làm giằng giữa (25x25x340)", 'type' => "CBG"],
            ['name' => "Hạ cấp làm cọc lều thú cưng 12x12x460", 'type' => "CBG"],
            ['name' => "Hàng chờ sửa", 'type' => "VCN"],
            ['name' => "Hàng không sửa được", 'type' => "VCN"],
            ['name' => "Hạ cấp loại 2", 'type' => "VCN"],
            ['name' => "Hạ cấp loại 3", 'type' => "VCN"],
            ['name' => "Hạ cấp loại 1 DE", 'type' => "VCN"],
            ['name' => "Hạ cấp loại 1 DD", 'type' => "VCN"],
            ['name' => "Hạ cấp về DE RAW", 'type' => "VCN"],
            ['name' => "Hạ cấp loại 1 CD", 'type' => "VCN"],
            ['name' => "Hạ cấp loại 1 EE", 'type' => "VCN"],

        ];
        DB::table("QChandle")->insert($data);
    }
}
